In [1]:
import numpy as np

In [2]:
l = [
    [1,2,3],
    [4,5,6]
] # shape: 3,2 <three columns, two rows>

arr = np.array(l)

In [3]:
l = [1,2,3,4,5]
a = np.array(l)

print(a)

print(a.shape)

[1 2 3 4 5]
(5,)


In [4]:
a = np.zeros((3,4), dtype=np.int8)

print(a)
print(a.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
(3, 4)


In [5]:
a = np.full((3,4), 10.2)

print(a)
print(a.shape)

[[10.2 10.2 10.2 10.2]
 [10.2 10.2 10.2 10.2]
 [10.2 10.2 10.2 10.2]]
(3, 4)


In [6]:
a = np.random.random((2,2))
np.random.seed(2)
print(a)

[[0.02852156 0.03438487]
 [0.3467036  0.83873951]]


In [7]:
a = np.arange(0,30,5)

print(a)


[ 0  5 10 15 20 25]


In [8]:
a = arr
print(a)
print(a.shape)
a = a.reshape((2,3))
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [9]:
a = arr
print(a, a.shape)
a = a.flatten()
print(a, a.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[1 2 3 4 5 6] (6,)


In [10]:
a = arr
new = a.astype(np.float16)
print(new)
print(new.dtype)



[[1. 2. 3.]
 [4. 5. 6.]]
float16


In [11]:
a = arr
print(a.T)
print(a.T.dtype)



[[1 4]
 [2 5]
 [3 6]]
int64


In [12]:
a = np.array([
    [1,2,3,4],
    [5,2,4,2],
    [5,9,2,0],
    [1,2,0,1]
])

print(a[:1,:3])
print(a[2:,1:])

[[1 2 3]]
[[9 2 0]
 [2 0 1]]
